### ISSUE TITLE
Upgrade to latest master branch

### ISSUE THREAD

**Issue by lucasjinreal** [PotatoProject/Leaflet#53] opened 2021-01-04 04:51 UTC
Can u guys check if project still can run on master branch??

Please check this issue:

https://github.com/flutter/flutter/issues/72216

**Comment by dvd-bnc** [comment] 2021-01-04 09:57
What branch of the repo are you using?

**Comment by lucasjinreal** [comment] 2021-01-04 10:07
@HrX03 Im using default main

**Comment by dvd-bnc** [comment] 2021-01-04 10:09
Did you try upgrading flutter? Cuz i got the error many times too but I just patch the local flutter repo. Btw it shouldn't be an issue specifically with code i use but mostly with null-safe code. To reproduce you can just create a blank project and import the flutter_localizations lib iirc

**Comment by lucasjinreal** [comment] 2021-01-04 10:12
@HrX03  thank u for your information. Im tried upgrade just yestorday night. no luck.
I don't know how to patch local flutter repo. Im just clone code and flutter run.

Can u patch this repo to fix this issue? Since some naive learner hard to investigate which reason exactly could be.

**Comment by dvd-bnc** [comment] 2021-01-04 10:13
Unfortunately I can't really patch the thing up from my side, mostly because I need the code that causes the issue. A possible patch would be to make the entire project null safe but it's not possible right now because of some libs still not being null safe

**Comment by lucasjinreal** [comment] 2021-01-04 10:18
@HrX03 I see... so that make everyone patch their official code to make this repo run also not a sustainable way.. Do u guys think about make a refactor version of it and compatible with official flutter code? I think from one way or another there must be someway to make it done.

**Comment by dvd-bnc** [comment] 2021-01-04 10:20
Yea as I told ya the only way is to either make the repo null safe (which we can't because of some packages being not ready yet) or remove the libraries that cause the import of the lib (which i pretty much know which it is but I really need it)

**Comment by lucasjinreal** [comment] 2021-01-04 10:45
@HrX03  Haha, you really need it, so let's keep it. BTW, what do you mean other lib not ready for null safe? Is that a feature effects all code in a lib? I am new to flutter and I really want to run this rep since I like the grid view and it's check list in a note. 

Do u know how to patch my local flutter repo ? Can u upgrade some doc in readme so that other people can also follow?

**Comment by dvd-bnc** [comment] 2021-01-04 10:47
If you want to make your app null safe every dependency you have should also be null safe, else you can't run on full null safe mode. Also for the patching steps i can add the steps on readme whenever I get on my pc

**Comment by lucasjinreal** [comment] 2021-01-04 10:48
@HrX03  thanks ! that's really helpful!

**Comment by dvd-bnc** [comment] 2021-05-11 18:03
took long enough but we now run completely on latest master, good to go and closing

**Closed as completed by dvd-bnc** 2021-05-11 18:03 UTC

**Comment by lucasjinreal** [comment] 2021-05-12 04:01
@HrX03 thank u!
