### ISSUE TITLE
Can't unlock notes

### ISSUE THREAD

**Issue by manaafi** [PotatoProject/Leaflet#4] opened 2019-10-12 17:51 UTC
Notes locked with a 4-digit pin can't be unlocked; only 3 digits can be entered before it shows "Wrong PIN".

**Comment by dvd-bnc** [comment] 2019-10-12 17:53
Hm interesting report, i actually tried to put a pin with 4 digits (classic "1234") but when going to unlock it actually managed to do so. Can you send a video/screen or some other details that can help me reproduce the issue? thanks

**Comment by dvd-bnc** [comment] 2019-10-12 17:56
ok i just tried with a pin like 0000 and it seems i've found another error where 0000 its being converted in 0 because its an int, i should recreate the db entry or rework the pin save logic so the content won't be lost (tho this seems harder)

**Comment by manaafi** [comment] 2019-10-12 18:04
Thanks, I locked my notes with a pin starting from 0 (say 0987), and now i tried and unlocked with 987.👍

**Comment by dvd-bnc** [comment] 2019-10-12 18:05
heh np, ill try to fix it asap, thanks for the report anyways

**Comment by manaafi** [comment] 2019-10-12 18:50
Welcome. Really liked this app🙌.
Also, not sure to open another issue as it ain't a big deal, but I have to scroll through the unlock screen to type in the digits, kinda inconvenient. Attached screenrecord. Some aspect-ratio issue? 
And notice the glitch when deleting a note (when it's the only one present) in the second video.
Btw, options like deleting should be hidden for locked notes...right?
[zippp.zip](https://github.com/HrX03/PotatoNotes/files/3721033/zippp.zip)

**Comment by dvd-bnc** [comment] 2019-10-12 18:53
for the pin thing, thats the most i can do, cuz else i should have to resize all widgets and idk, you can try making your dpi larger. as of deleted notes thing, AgentFabulous just made a PR that i merged that fixes that, you just gotta wait for a new build

**Comment by dvd-bnc** [comment] 2019-10-15 20:39
ok so i'm closing this issue as the last commits fix the problem, to do so just install the update from xda labs, go to settings and click "Regenerate database entries" and you're all set, you just need to re set the broken pins and all should be fine, thanks for the report anyways

**Closed as completed by dvd-bnc** 2019-10-15 20:39 UTC
