### ISSUE TITLE
"Reminder" feature is not working

### ISSUE THREAD

**Issue by NandishStark** [PotatoProject/Leaflet#58] opened 2021-03-14 15:10 UTC
Whenever I use reminder feature, it closes the app and deletes the note also.

**Comment by NandishStark** [comment] 2021-05-17 21:19
Hello??? Anybody??????

**Comment by dvd-bnc** [comment] 2021-05-17 22:10
Oops sorry, anyways duplicate of #40 where i also explain future plans and all, closing

**Closed as completed by dvd-bnc** 2021-05-17 22:10 UTC
