### ISSUE TITLE
Refreshing content causes note data loss

### ISSUE THREAD

**Issue by AnonRS3** [PotatoProject/Leaflet#9] opened 2020-02-18 03:53 UTC
If I create a note or change a notes color, those changes aren't saved if I pull to refresh from the main page. The changed note colors revert back to their former colors and some notes have disappeared completely.

**Comment by dvd-bnc** [comment] 2020-02-22 19:35
The problem here could be:
- API request with color prolly returns error, could be malformed json or input in general
- not handling color encoding correctly, but now that I think about it it doesn't make any sense, it'd save but show a wrong color, so it's prolly the first one

**Comment by AnonRS3** [comment] 2020-02-23 00:23
@HrX03 a similar issue happens with viewing notes in the trash. If you empty the trash, then pull to refresh, sometimes the emptied trash will refill with the notes that are supposed to be deleted.

**Comment by dvd-bnc** [comment] 2020-02-23 10:21
This seems like an issue that is caused by the user refreshing too soon, even before the thing finished sending the request. After emptying the trash, try to wait some seconds or so and then pull, just to confirm that the problem is the one i stated

**Comment by AnonRS3** [comment] 2020-02-23 16:07
@HrX03 I found that if I create a brand new note and change it's color from the editing screen, then back out to the home page, the note immediately disappears without refreshing at all. Creating a note without changing the color first does not make the note disappear immediately. 

I also found that if I change the color of a note from the home screen (via tap and hold) the note reverts back to its original color immediately without refreshing the page at all. 

The emptying trash issue still occurs even without pulling to refresh manually. If I click the empty trash option, then wait a second or two, the note that was just deleted reappears.

**Comment by AnonRS3** [comment] 2020-02-23 16:11
The trash issue seems directly related to the sync interval. I tried changing the interval to different levels and the emptied trash refills itself every time the app syncs.

**Comment by dvd-bnc** [comment] 2020-02-23 16:15
For solving the trash issue I should probably make the sync mechanism stop syncing if there are other sync operations going on, I will try asap.
For the color issue, it should be a bad json input prolly

**Comment by dvd-bnc** [comment] 2020-02-23 21:34
small update on color issue: it appears that its a database problem, apparently the color int is too big for the database standard int type, but i already told to the server guy to make the column bigger so it should be fixed pretty soon. and it won't even require an update from my end yay!

**Comment by dvd-bnc** [comment] 2021-05-11 18:05
this has been fixed and doesnt happen anymore with latest sync implementation, closing

**Closed as completed by dvd-bnc** 2021-05-11 18:05 UTC
